name = "cuibonobo-website"
pages_build_output_dir = "./build"

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-08-15"

[[d1_databases]]
binding = "STACK_DB"
database_name = "stack_db"
database_id = "74d928c9-2649-4a29-84bb-187562fb48c9"
